name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        description: Version type
        options:
        - patch
        - minor
        - major
jobs:
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install, test and build
        run: yarn && yarn build
      - name: Update Package.json version and tag
        run: |
          git config user.name "Hargne"
          git config user.email "johan.hargne@gmail.com"
          versionType="${{ github.event.inputs.version }}"
          new_version=$(npm version "$versionType" --no-git-tag-version)
          git add .
          git commit -m "Released $new_version"
          git tag "$new_version"
          git push origin --tags
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
